const companies = [
  "Tata Consultancy Services (TCS)",
  "Infosys",
  "Wipro",
  "HCL Technologies",
  "Tech Mahindra",
  "Accenture",
  "Capgemini",
  "Cognizant",
  "IBM",
  "Microsoft",
  "Google",
  "Amazon",
  "Oracle",
  "Adobe",
  "Deloitte",
  "EY",
  "KPMG",
  "PwC",
  "Reliance Industries",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "State Bank of India",
  "Flipkart",
  "PhonePe",
  "Paytm",
  "Swiggy",
  "Zomato",
];

export default companies;