import {
  BadgeIndianRupee,
  Banknote,
  BadgeCheck,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CreditCard,
  FileDigit,
  FileText,
  Fingerprint,
  Globe2,
  HeartHandshake,
  Home,
  IdCard,
  Landmark,
  Mail,
  Map,
  MapPin,
  MessagesSquare,
  NotebookTabs,
  Phone,
  ReceiptIndianRupee,
  ShieldCheck,
  Signature,
  Tag,
  User,
  UserRoundPlus,
  Users,
  WalletCards,
} from "lucide-react";

const ICON_RULES = [
  [/loanamount|loan amount|amount/i, BadgeIndianRupee],
  [/loantenure|tenure/i, CalendarDays],
  [/purpose/i, NotebookTabs],
  [/referral/i, Tag],
  [/firstname|lastname|fullname|fathername|mothername|name/i, User],
  [/dob|dateofbirth|birth/i, CalendarDays],
  [/gender/i, Users],
  [/marital/i, HeartHandshake],
  [/email/i, Mail],
  [/mobile|phone/i, Phone],
  [/pan/i, IdCard],
  [/aadhaar|aadhar/i, Fingerprint],
  [/voter/i, IdCard],
  [/passport/i, FileText],
  [/country/i, Globe2],
  [/state/i, Map],
  [/city/i, Building2],
  [/pin|pincode/i, MapPin],
  [/address/i, Home],
  [/residential|residence/i, Home],
  [/year.*address/i, CalendarDays],
  [/rent/i, WalletCards],
  [/employment/i, BriefcaseBusiness],
  [/company/i, Building2],
  [/designation|jobtitle/i, BriefcaseBusiness],
  [/salary|income|turnover|expense|emi|processing/i, Banknote],
  [/gst/i, ReceiptIndianRupee],
  [/business|industry/i, Building2],
  [/coapplicant|guarantor/i, UserRoundPlus],
  [/relationship/i, HeartHandshake],
  [/consent/i, ShieldCheck],
  [/document|upload/i, FileText],
  [/signature/i, Signature],
  [/otp/i, MessagesSquare],
  [/verification|verified/i, BadgeCheck],
  [/account|bank/i, Landmark],
  [/credit/i, CreditCard],
  [/policy|terms/i, ShieldCheck],
  [/office/i, Building2],
  [/annual/i, ReceiptIndianRupee],
  [/zipcode|postal/i, MapPin],
];

export function getFieldIcon(name = "", label = "") {
  const key = `${name} ${label}`.replace(/[^a-z0-9 ]/gi, "");

  for (const [pattern, Icon] of ICON_RULES) {
    if (pattern.test(key)) return Icon;
  }

  return FileDigit;
}
